### ISSUE TITLE
Error when specifying dim parameter

### ISSUE THREAD

**Issue by kevinsawicki** [nasa/NASA-APIs#13] opened 2016-04-02 02:47 UTC
The following url displays an error related to the `dim` parameter:

https://api.nasa.gov/planetary/earth/imagery?dim=0.025&lon=100.75&lat=1.5&date=2014-02-01&cloud_score=True&api_key=DEMO_KEY

``` json
{
  "message": "Admins have been notified.",
  "error": "unsupported operand type(s) for /: 'unicode' and 'int'"
}
```

The docs say `dim` is supported and defaults to `0.025` but an error is returned when called with that value.

<img width="871" alt="screen shot 2016-04-01 at 7 45 58 pm" src="https://cloud.githubusercontent.com/assets/671378/14224030/8269fbfa-f842-11e5-923a-078197606ad3.png">

**Comment by albertoxamin** [comment] 2017-04-29 14:30
this issue is still present.

**Comment by jakub-m** [comment] 2017-07-10 21:37
Duplicate of https://github.com/nasa/api-docs/issues/63

**Comment by JustinGOSSES** [comment] 2019-02-06 17:17
That link no longer returns an error.

**Closed by JustinGOSSES** 2019-02-06 17:17 UTC
